name: Tests

on:
  push:
  pull_request:

jobs:
  run_tests:
    name: ${{ matrix.host-os }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.host-os }}
    strategy:
      matrix:
        host-os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "3.8", "3.9"]
      fail-fast: false

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Set env vars
        run: |
          export REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}  # just the repo, as opposed to org/repo
          echo "REPOSITORY_NAME=${REPOSITORY_NAME}" >> $GITHUB_ENV

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }} with conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ${{ env.REPOSITORY_NAME }}-py${{ matrix.python-version }}
          auto-update-conda: true
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}

      - name: Install the package and its dependencies
        run: |
          set -vxeo pipefail
          conda env list
          if [ "$RUNNER_OS" != "Windows" ]; then
              pip install --upgrade pip wheel
          fi
          pip install -v .
          pip install -r requirements-dev.txt
          pip list
          conda list

      - name: Test with pytest
        run: |
          set -vxeuo pipefail
          pytest -s -vv
